name: Cronjob for Sync Image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"
  pull_request:
    branches:
      - 'main'

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger list
        env:
          HI_REGISTRY: ${{ secrets.HI_REGISTRY }}
          QCR_REGISTRY: ${{ secrets.QCR_REGISTRY }}
          FLAT_REGISTRY: ${{ secrets.FLAT_REGISTRY }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -e

          . func.sh
          len=$(jq '. | length' image-list.json)
          for idx in $(seq 0 $((len-1))); do
          
            image="$(jq -r '.['${idx}'].image' image-list.json)"
            tag_reg="$(jq -r '.['${idx}'].tagReg' image-list.json)"
            sync_type="$(jq -r '.['${idx}'].type' image-list.json)"
            
            latest1=$(skopeo list-tags --creds ${{ secrets.HI_CREDS }} docker://$(transform_oci_image_url ${sync_type} ${image}) | jq -r '.Tags[]' | grep -E "${tag_reg}" | sort -Vr | head -n 1)
            latest_tag=$(skopeo list-tags docker://${image} | jq -r '.Tags[]' | grep -E "${tag_reg}" | sort -Vr | head -n 1)

            if [[ ${latest1} != ${latest_tag} ]]; then
              echo "Sync ${image}:${latest_tag}"

              json_data=$(jq -n --arg image "${image}:${latest_tag}" --arg sync_type "${sync_type}" '
            {
              "ref": "main",
                "inputs": {
                  "image": $image,
                  "type": $sync_type
              }
            }
            ')
              curl -sfS -X POST \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2026-03-10" \
                -H "Content-Type: application/json" \
                ${{ github.api_url }}/repos/${GITHUB_REPOSITORY}/actions/workflows/sync.yml/dispatches \
                -d "$json_data"
              
              # gh workflow run sync.yml -R ${GITHUB_REPOSITORY} --ref main -f image="${image}:${latest_tag}" -f "type=${sync_type}"
            fi
          done
