name: Cronjob for Sync Image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"
  pull_request:
    branches:
      - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger list
        shell: bash
        run: |
          set -ex

          . func.sh
          jq -c '.[]' image-list.txt | while read line; do
            SRC="$(echo $line | jq -r '.image')"
            tagReg="$(echo $line | jq -r '.tagReg')"

            latest1=(skopeo list-tags --creds ${{ secrets.QCR_CREDS }} docker://$(transform_oci_image_url flat ${SRC}) | grep -E "'"${tagReg}"'" | sort -Vr | head -n 1)
            latest2=(skopeo list-tags docker://${SRC} | grep -E "'"${tagReg}"'" | sort -Vr | head -n 1)
            echo ${latest1}
            echo ${latest2}
          done
