name: Cronjob for Sync Image

on:
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * *"
  pull_request:
    branches:
      - 'main'

permissions:
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Trigger list
        env:
          HI_REGISTRY: ${{ secrets.HI_REGISTRY }}
          QCR_REGISTRY: ${{ secrets.QCR_REGISTRY }}
          FLAT_REGISTRY: ${{ secrets.FLAT_REGISTRY }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          set -e

          cat -n $0
          . func.sh
          len=$(jq '. | length' image-list.json)
          for idx in $(seq 0 $((len-1))); do
          
            SRC="$(jq -r '.['${idx}'].image' image-list.json)"
            tagReg="$(jq -r '.['${idx}'].tagReg' image-list.json)"
            
            latest1=$(skopeo list-tags --creds ${{ secrets.HI_CREDS }} docker://$(transform_oci_image_url flat ${SRC}) | jq -r '.Tags[]' | grep -E "${tagReg}" | sort -Vr | head -n 1)
            latest2=$(skopeo list-tags docker://${SRC} | jq -r '.Tags[]' | grep -E "${tagReg}" | sort -Vr | head -n 1)

            # if [[ ${latest1} != ${latest2} ]]; then
            set -x
            if [[ ${latest1} == ${latest2} ]]; then
              gh workflow run sync.yml -R ${GITHUB_REPOSITORY} --ref main -f image="${SRC}:${latest2}" -f "type=acr"
            fi
            set +x
          done
