name: Sync Image to Private Registry
run-name: Image - ${{ inputs.image || github.event.head_commit.message }}

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      image:
        description: "Source images (comma-separated, e.g. docker.io/golang:1.26.2-bookworm)"
        required: true
        type: string
        default: "docker.io/golang:1.26.2-bookworm"
      type:
        description: "Source images type: hierarchical,flat,qcr"
        required: true
        type: choice
        default: "hierarchical"
        options:
         - hierarchical
         - flat
         - qcr

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Parse input
        id: parse
        shell: bash
        run: |
          set -ex

          echo "skip=false" >> $GITHUB_OUTPUT

          if [[ "${{ github.event_name }}" == "push" ]]; then
            msg="${{ github.event.head_commit.message }}"
            echo "commit message: $msg"
            msg="$(echo "$msg" | head -n 1)"

            if [[ "$msg" =~ ^flat-sync:\ (.+)$ ]]; then
              value="${BASH_REMATCH[1]}"
              {
                echo "value<<EOF"
                echo "$value"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"
              echo "type=flat" >> $GITHUB_OUTPUT

            elif [[ "$msg" =~ ^qcr-sync:\ (.+)$ ]]; then
              value="${BASH_REMATCH[1]}"
              {
                echo "value<<EOF"
                echo "$value"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"
              echo "type=qcr" >> $GITHUB_OUTPUT

            elif [[ "$msg" =~ ^hi-sync:\ (.+)$ ]]; then
              value="${BASH_REMATCH[1]}"
              {
                echo "value<<EOF"
                echo "$value"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"
              echo "type=hi" >> $GITHUB_OUTPUT

            else
              echo "skip=true" >> $GITHUB_OUTPUT
              echo "type=xxx" >> $GITHUB_OUTPUT
            fi

          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            {
              echo "value<<EOF"
              echo "${{ inputs.image }}"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
            if [[ "${{ inputs.type }}" = "hierarchical" ]]; then
              echo "type=hi" >> $GITHUB_OUTPUT

            elif [[ "${{ inputs.type }}" = "qcr" ]]; then
              echo "type=qcr" >> $GITHUB_OUTPUT

            elif [[ "${{ inputs.type }}" = "flat" ]]; then
              echo "type=flat" >> $GITHUB_OUTPUT

            else
              echo "skip=true" >> $GITHUB_OUTPUT
              echo "type=xxx" >> $GITHUB_OUTPUT
            fi

          fi

      - name: 🚀 Sync Images
        if: steps.parse.outputs.skip != 'true'
        env:
          HI_REGISTRY: ${{ secrets.HI_REGISTRY }}
          QCR_REGISTRY: ${{ secrets.QCR_REGISTRY }}
          FLAT_REGISTRY: ${{ secrets.FLAT_REGISTRY }}
        shell: bash
        run: |
          SRC="${{ steps.parse.outputs.value }}"
          echo "镜像: $SRC"
          echo
          skopeo --version

          . func.sh
          set -x
          if [[ ${{ steps.parse.outputs.type }} = hi ]]; then
            DEST="$(transform_oci_image_url hi ${SRC})"
            echo "Starting sync: $SRC -> $DEST"

            skopeo copy --all --src-tls-verify=true --dest-tls-verify=true \
              --dest-creds "${{ secrets.HI_CREDS }}" \
              "docker://$SRC" \
              "docker://$DEST"

          elif [[ ${{ steps.parse.outputs.type }} = qcr ]]; then
            DEST="$(transform_oci_image_url qcr ${SRC})"
            echo ">>> Syncing: $SRC -> $DEST"

            skopeo copy --all --src-tls-verify=true --dest-tls-verify=true \
              --dest-creds "${{ secrets.QCR_CREDS }}" \
              "docker://$SRC" \
              "docker://$DEST"

          elif [[ ${{ steps.parse.outputs.type }} = flat ]]; then
            DEST="$(transform_oci_image_url flat ${SRC})"
            echo ">>> Syncing: $SRC -> $DEST"

            skopeo copy --all --src-tls-verify=true --dest-tls-verify=true \
              --dest-creds "${{ secrets.FLAT_CREDS }}" \
              "docker://$SRC" \
              "docker://$DEST"
          fi

          echo ">>> Done: $SRC"
